name       : kget
version    : 19.12.1
release    : 26
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/kget-19.12.1.tar.xz : 33b043857b3d1c55d877d1c3af2bcc46feefe15019b7af40a9951c16e288658c
homepage   : https://kde.org/applications/internet/org.kde.kget
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.download
summary    : Download manager by KDE
description: |
    KGet is a versatile and user-friendly download manager.
builddeps  :
    - pkgconfig(libmms)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kitemviews-devel
    - kcmutils-devel
    - kdelibs4support-devel
    - knotifyconfig-devel
    - kwallet-devel
    - libboost-devel
    - libgcrypt-devel
    - libktorrent-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
