name       : kget
version    : 18.08.2
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kget-18.08.2.tar.xz : 8e8bce7179b175b04e9c74382fd822f048c5b1c55f2ec985dba973ac329e66c1
license    :
    - GFDL-1.2
    - GLPL-2.1
    - GPL-2.0
component  : network.download
summary    : Download manager by KDE
description: |
    KGet is a versatile and user-friendly download manager.
builddeps  :
    - pkgconfig(libmms)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kcmutils-devel
    - kdelibs4support-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libktorrent-devel
    - plasma-workspace-devel
    - solid-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
