name       : kget
version    : 21.04.1
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kget-21.04.1.tar.xz : 3c590d73774a444340ee106fdbc22a91045c827e610b2c2b527d252ddb587d28
homepage   : https://kde.org/applications/internet/org.kde.kget
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.download
summary    : Download manager by KDE
description: |
    KGet is a versatile and user-friendly download manager.
builddeps  :
    - pkgconfig(libgcrypt)
    - pkgconfig(libmms)
    - pkgconfig(qca2-qt5)
    - gpgme-qt-devel
    - kcmutils-devel
    - kdelibs4support-devel
    - knotifyconfig-devel
    - kwallet-devel
    - libboost-devel
    - libktorrent-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
