name       : kget
version    : 21.12.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kget-21.12.0.tar.xz : 5f55ea13f150ac063f9b2e04ffad9c0b86477a39158adcf4a319ec2a483aa535
homepage   : https://kde.org/applications/internet/org.kde.kget
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.download
summary    : Download manager by KDE
description: |
    KGet is a versatile and user-friendly download manager.
builddeps  :
    - pkgconfig(libgcrypt)
    - pkgconfig(libmms)
    - pkgconfig(qca2-qt5)
    - gpgme-qt-devel
    - kcmutils-devel
    - kdelibs4support-devel
    - knotifyconfig-devel
    - kwallet-devel
    - libboost-devel
    - libktorrent-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
