name       : kget
version    : 18.12.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/kget-18.12.2.tar.xz : 6d06d22cbef14cb935040e29750702f470bde8bce3d9d62660287c2a51189c60
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.download
summary    : Download manager by KDE
description: |
    KGet is a versatile and user-friendly download manager.
builddeps  :
    - pkgconfig(libmms)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kcmutils-devel
    - kdelibs4support-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libktorrent-devel
    - plasma-workspace-devel
    - solid-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
