name       : kget
version    : 22.04.2
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/kget-22.04.2.tar.xz : 4f75430fe14badd7562e5040561b5e09cf595a835ac29ce4fbf9e15de5605744
homepage   : https://kde.org/applications/internet/org.kde.kget
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.download
summary    : Download manager by KDE
description: |
    KGet is a versatile and user-friendly download manager.
builddeps  :
    - pkgconfig(libgcrypt)
    - pkgconfig(libmms)
    - pkgconfig(qca2-qt5)
    - gpgme-qt-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwallet-devel
    - libboost-devel
    - libktorrent-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
