name       : kget
version    : 18.04.2
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kget-18.04.2.tar.xz : 91e7559cd7a1fb724791da777532f058801bf54e6ab7405e82380416edf90144
license    :
    - GFDL-1.2
    - GLPL-2.1
    - GPL-2.0
component  : network.download
summary    : Download manager by KDE
description: |
    KGet is a versatile and user-friendly download manager.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libmms)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kcmutils-devel
    - kdelibs4support-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libktorrent-devel
    - plasma-workspace-devel
    - solid-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
