name       : kget
version    : 18.08.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kget-18.08.0.tar.xz : 24ebb10a9c666c1c28a1cea06787ffa5551f52f9d44c20f50a9028fc9c86f76e
license    :
    - GFDL-1.2
    - GLPL-2.1
    - GPL-2.0
component  : network.download
summary    : Download manager by KDE
description: |
    KGet is a versatile and user-friendly download manager.
builddeps  :
    - pkgconfig(libmms)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kcmutils-devel
    - kdelibs4support-devel
    - kio-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libassuan-devel
    - libboost-devel
    - libktorrent-devel
    - plasma-workspace-devel
    - solid-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
