name       : kget
version    : 19.08.2
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kget-19.08.2.tar.xz : e93795eec8f51cac2719ab31cfa6f5f4f642b166ffbb3f876ab3c866a4cd7df1
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : network.download
summary    : Download manager by KDE
description: |
    KGet is a versatile and user-friendly download manager.
builddeps  :
    - pkgconfig(libmms)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kitemviews-devel
    - kcmutils-devel
    - kdelibs4support-devel
    - knotifyconfig-devel
    - kwallet-devel
    - libboost-devel
    - libgcrypt-devel
    - libktorrent-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
